[project]
name = "cyberneura-id-svelte-testbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.2",
]
[project.optional-dependencies]
# uv sync --extra test
test = []
